/*SCRIPT DE CRIAÇÃÕ˜DE BANCO DE DADOS*/

CREATE DATABASE CARRINHO;

USE CARRINHO;

CREATE TABLE ADMIN (
	ID INTEGER NOT NULL PRIMARY KEY,
    NOME VARCHAR(50) NOT NULL,
    SENHA VARCHAR(20) NOT NULL
);

CREATE TABLE PRODUTO (
	CODIGO INTEGER NOT NULL PRIMARY KEY,
    MARCA VARCHAR(50) NOT NULL,
    QTDE INTEGER NOT NULL,
    PRECO DECIMAL(6,2) NOT NULL,
    IMG VARCHAR(20) NOT NULL,
    ADMIN_ID INTEGER NOT NULL,
    FOREIGN KEY (ADMIN_ID) REFERENCES ADMIN(ID),
);

CREATE TABLE CLIENTE (
	ID_CLIENTE INTEGER NOT NULL PRIMARY KEY,
    EMAIL VARCHAR(50) NOT NULL,
    SENHA VARCHAR(20) NOT NULL,
    NOME VARCHAR(50) NOT NULL
);

CREATE TABLE CONTA (
    SENHA INTEGER NOT NULL,
    AGENCIA INTEGER NOT NULL,
    OPERACAO INTEGER NOT NULL,
    CONTA INTEGER NOT NULL,
    CREDITO DECIMAL(6,2) NOT NULL,
    BANCO INTEGER NOT NULL,
    CLIENTE INTEGER,
    FOREIGN KEY (CLIENTE) REFERENCES CLIENTE(ID_CLIENTE),
    CONSTRAINT PK_CONTA PRIMARY KEY (SENHA,AGENCIA,CONTA,BANCO)
);